package skill

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// Reference renders the command tree as the skill's references/cli.md: every
// command with its description, usage, flags and examples, in the order of
// `--help`. Cobra's own help and completion commands are left out.
func Reference(root *cobra.Command) string {
	var b strings.Builder
	b.WriteString("# Command reference\n\n")
	b.WriteString("<!-- Generated by `go generate ./skills` from the command tree. Do not edit. -->\n\n")
	fmt.Fprintf(&b, "Every `%s` command in this release with its flags, as `--help` shows them.\n", root.Name())
	b.WriteString("Every command also accepts `-h, --help`.\n")
	for _, cmd := range commands(root) {
		writeCommand(&b, cmd)
	}
	return b.String()
}

// Leaves returns the commands that do the work: runnable commands without
// subcommands, excluding Cobra's own help and completion.
func Leaves(root *cobra.Command) []*cobra.Command {
	var leaves []*cobra.Command
	for _, cmd := range commands(root) {
		if cmd.Runnable() && !hasSubcommands(cmd) {
			leaves = append(leaves, cmd)
		}
	}
	return leaves
}

func commands(cmd *cobra.Command) []*cobra.Command {
	list := []*cobra.Command{cmd}
	for _, sub := range cmd.Commands() {
		if sub.IsAvailableCommand() && !builtin(sub) {
			list = append(list, commands(sub)...)
		}
	}
	return list
}

func builtin(cmd *cobra.Command) bool {
	return cmd.Parent() == cmd.Root() && (cmd.Name() == "help" || cmd.Name() == "completion")
}

func hasSubcommands(cmd *cobra.Command) bool {
	for _, sub := range cmd.Commands() {
		if sub.IsAvailableCommand() && !builtin(sub) {
			return true
		}
	}
	return false
}

func writeCommand(b *strings.Builder, cmd *cobra.Command) {
	fmt.Fprintf(b, "\n## %s\n\n", cmd.CommandPath())
	if text := description(cmd); text != "" {
		b.WriteString(text + "\n\n")
	}
	usage := cmd.UseLine()
	if hasSubcommands(cmd) {
		usage = cmd.CommandPath() + " [command]"
	}
	fmt.Fprintf(b, "```text\n%s\n```\n", usage)

	switch {
	case !cmd.HasParent():
		writeFlags(b, "Global flags, accepted by every command in any position:", cmd.PersistentFlags())
	case hasSubcommands(cmd):
		writeFlags(b, fmt.Sprintf("Flags of every `%s` command:", cmd.CommandPath()), cmd.PersistentFlags())
	default:
		writeFlags(b, "Flags:", cmd.LocalNonPersistentFlags())
	}

	if cmd.Example != "" {
		b.WriteString("\nExamples:\n\n```sh\n")
		for _, line := range strings.Split(cmd.Example, "\n") {
			b.WriteString(strings.TrimSpace(line) + "\n")
		}
		b.WriteString("```\n")
	}
}

func description(cmd *cobra.Command) string {
	text := cmd.Long
	if text == "" {
		text = cmd.Short
	}
	if text == cmd.Name() {
		return ""
	}
	return strings.TrimSpace(text)
}

func writeFlags(b *strings.Builder, title string, flags *pflag.FlagSet) {
	var lines []string
	flags.VisitAll(func(f *pflag.Flag) {
		if f.Hidden || f.Name == "help" {
			return
		}
		name := "--" + f.Name
		if f.Shorthand != "" {
			name = "-" + f.Shorthand + ", " + name
		}
		varname, usage := pflag.UnquoteUsage(f)
		if varname != "" {
			name += " " + varname
		}
		line := fmt.Sprintf("- `%s`", name)
		if _, ok := f.Annotations[cobra.BashCompOneRequiredFlag]; ok {
			line += " (required)"
		}
		line += ": " + usage
		if !zeroDefault(f) {
			if f.Value.Type() == "string" {
				line += fmt.Sprintf(" (default %q)", f.DefValue)
			} else {
				line += fmt.Sprintf(" (default %s)", f.DefValue)
			}
		}
		lines = append(lines, line)
	})
	if len(lines) == 0 {
		return
	}
	fmt.Fprintf(b, "\n%s\n\n%s\n", title, strings.Join(lines, "\n"))
}

// zeroDefault mirrors pflag, which leaves zero defaults out of the help.
func zeroDefault(f *pflag.Flag) bool {
	switch f.Value.Type() {
	case "bool":
		return f.DefValue == "false"
	case "string":
		return f.DefValue == ""
	case "duration":
		return f.DefValue == "0" || f.DefValue == "0s"
	}
	switch f.DefValue {
	case "", "0", "[]", "<nil>":
		return true
	}
	return false
}
