// Code generated by github.com/kamilsk/egg. DO NOT EDIT.

//go:build tools

package tools

//go:generate go install cuelang.org/go/cmd/cue
//go:generate go install github.com/golang/mock/mockgen
//go:generate go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint
//go:generate go install github.com/goreleaser/goreleaser/v2
//go:generate go install golang.org/x/tools/cmd/goimports
//go:generate go install golang.org/x/vuln/cmd/govulncheck
